var annotated_dup =
[
    [ "weblog", "namespaceweblog.html", [
      [ "ALogOutputter", "classweblog_1_1_a_log_outputter.html", "classweblog_1_1_a_log_outputter" ],
      [ "LogData", "classweblog_1_1_log_data.html", "classweblog_1_1_log_data" ],
      [ "Logger", "classweblog_1_1_logger.html", "classweblog_1_1_logger" ],
      [ "LogOutputterConsole", "classweblog_1_1_log_outputter_console.html", "classweblog_1_1_log_outputter_console" ],
      [ "LogOutputterFile", "classweblog_1_1_log_outputter_file.html", "classweblog_1_1_log_outputter_file" ]
    ] ],
    [ "AcceptConnectionsTest", "class_accept_connections_test.html", "class_accept_connections_test" ],
    [ "AutoindexHandler", "class_autoindex_handler.html", "class_autoindex_handler" ],
    [ "CheckForTimeoutTest", "class_check_for_timeout_test.html", "class_check_for_timeout_test" ],
    [ "ConfigFile", "struct_config_file.html", "struct_config_file" ],
    [ "ConfigFileParser", "class_config_file_parser.html", "class_config_file_parser" ],
    [ "ConfigServer", "struct_config_server.html", "struct_config_server" ],
    [ "Connection", "struct_connection.html", "struct_connection" ],
    [ "ConnectionReceiveHeaderTest", "class_connection_receive_header_test.html", "class_connection_receive_header_test" ],
    [ "ConnectionSendResponseTest", "class_connection_send_response_test.html", "class_connection_send_response_test" ],
    [ "CreateVirtualServerTest", "class_create_virtual_server_test.html", "class_create_virtual_server_test" ],
    [ "Directory", "class_directory.html", "class_directory" ],
    [ "EpollWrapper", "class_epoll_wrapper.html", "class_epoll_wrapper" ],
    [ "FileSystemPolicy", "class_file_system_policy.html", "class_file_system_policy" ],
    [ "HTTPRequest", "struct_h_t_t_p_request.html", "struct_h_t_t_p_request" ],
    [ "InitVirtualServersTest", "class_init_virtual_servers_test.html", "class_init_virtual_servers_test" ],
    [ "InvalidConfigFileTests", "class_invalid_config_file_tests.html", "class_invalid_config_file_tests" ],
    [ "isDuplicateServerTest", "classis_duplicate_server_test.html", "classis_duplicate_server_test" ],
    [ "Location", "struct_location.html", "struct_location" ],
    [ "MockEpollWrapper", "class_mock_epoll_wrapper.html", "class_mock_epoll_wrapper" ],
    [ "MockFileSystemPolicy", "class_mock_file_system_policy.html", "class_mock_file_system_policy" ],
    [ "MockSocketPolicy", "class_mock_socket_policy.html", "class_mock_socket_policy" ],
    [ "OstreamInsertersTest", "class_ostream_inserters_test.html", "class_ostream_inserters_test" ],
    [ "ParseBodyTest", "class_parse_body_test.html", "class_parse_body_test" ],
    [ "ParseHeadersTest", "class_parse_headers_test.html", "class_parse_headers_test" ],
    [ "ParseRequestLineTest", "class_parse_request_line_test.html", "class_parse_request_line_test" ],
    [ "RegisterConnectionTest", "class_register_connection_test.html", "class_register_connection_test" ],
    [ "RegisterVirtualServerTest", "class_register_virtual_server_test.html", "class_register_virtual_server_test" ],
    [ "RequestParser", "class_request_parser.html", "class_request_parser" ],
    [ "ResponseBodyHandler", "class_response_body_handler.html", "class_response_body_handler" ],
    [ "ResponseBodyHandlerTest", "class_response_body_handler_test.html", "class_response_body_handler_test" ],
    [ "ResponseBuilder", "class_response_builder.html", "class_response_builder" ],
    [ "selectServerConfigTest", "classselect_server_config_test.html", "classselect_server_config_test" ],
    [ "Server", "class_server.html", "class_server" ],
    [ "ShutdownServerTest", "class_shutdown_server_test.html", "class_shutdown_server_test" ],
    [ "Socket", "struct_socket.html", "struct_socket" ],
    [ "SocketPolicy", "class_socket_policy.html", "class_socket_policy" ],
    [ "TargetResourceHandler", "class_target_resource_handler.html", "class_target_resource_handler" ],
    [ "TargetResourceHandlerTest", "class_target_resource_handler_test.html", "class_target_resource_handler_test" ],
    [ "URI", "struct_u_r_i.html", "struct_u_r_i" ],
    [ "ValidConfigFileTests", "class_valid_config_file_tests.html", "class_valid_config_file_tests" ]
];